import { DocumentItem, BureaucraticTask } from '../types';

export const INITIAL_MOCK_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-001',
    title: 'International Passport',
    doc_type: 'PASSPORT',
    category: 'IDENTITY',
    issuing_country: 'DEU',
    document_number: 'C489•••21',
    issue_date: '2021-04-12',
    expiry_date: '2031-04-12',
    status: 'ACTIVE',
    file_mime_type: 'application/pdf',
    file_size_bytes: 1428500,
  },
  {
    id: 'doc-002',
    title: 'Aadhaar Identity Card',
    doc_type: 'NATIONAL_ID',
    category: 'IDENTITY',
    issuing_country: 'IND',
    document_number: '[Aadhaar Redacted]',
    issue_date: '2019-08-15',
    expiry_date: null,
    status: 'ACTIVE',
    file_mime_type: 'image/jpeg',
    file_size_bytes: 845200,
  },
  {
    id: 'doc-003',
    title: 'B.Tech Degree Certificate',
    doc_type: 'DEGREE',
    category: 'EDUCATION',
    issuing_country: 'IND',
    document_number: 'DEG-2023-8821',
    issue_date: '2023-06-20',
    expiry_date: null,
    status: 'ACTIVE',
    file_mime_type: 'application/pdf',
    file_size_bytes: 2310000,
  },
  {
    id: 'doc-004',
    title: 'Schengen Incoming Health Insurance',
    doc_type: 'HEALTH_INSURANCE',
    category: 'TRAVEL',
    issuing_country: 'DEU',
    document_number: 'POL-992140',
    issue_date: '2026-01-10',
    expiry_date: '2026-10-30',
    status: 'EXPIRING_SOON',
    file_mime_type: 'application/pdf',
    file_size_bytes: 912000,
  },
  {
    id: 'doc-005',
    title: 'Income Tax Return (ITR-V)',
    doc_type: 'TAX_RETURN',
    category: 'TAXATION',
    issuing_country: 'IND',
    document_number: 'ACK-881920192',
    issue_date: '2024-07-28',
    expiry_date: '2025-07-31',
    status: 'EXPIRED',
    file_mime_type: 'application/pdf',
    file_size_bytes: 489000,
  }
];

export const INITIAL_MOCK_TASKS: BureaucraticTask[] = [
  {
    id: 'task-101',
    task_name: 'German National Student Visa (Section 16b AufenthG)',
    target_country: 'DEU',
    status: 'WAITING_DOCUMENTS',
    deadline: '2026-11-15',
    checklist_state: [
      {
        doc_type: 'PASSPORT',
        status: 'AVAILABLE',
        doc_id: 'doc-001',
        title: 'International Passport',
        expiry_date: '2031-04-12',
        notes: 'Valid for more than 3 months after intended stay.',
      },
      {
        doc_type: 'DEGREE',
        status: 'AVAILABLE',
        doc_id: 'doc-003',
        title: 'B.Tech Degree Certificate',
        expiry_date: null,
        notes: 'Anabin/ZAB recognized secondary or bachelor degree.',
      },
      {
        doc_type: 'HEALTH_INSURANCE',
        status: 'EXPIRING_SOON',
        doc_id: 'doc-004',
        title: 'Schengen Incoming Health Insurance',
        expiry_date: '2026-10-30',
        notes: 'Expires soon. Renewal or extension needed before appointment.',
      },
      {
        doc_type: 'BLOCKED_ACCOUNT_PROOF',
        status: 'MISSING',
        doc_id: null,
        title: null,
        expiry_date: null,
        notes: 'Proof of blocked account (min. €11,208/yr) not found in vault.',
      },
      {
        doc_type: 'ADMISSION_LETTER',
        status: 'MISSING',
        doc_id: null,
        title: null,
        expiry_date: null,
        notes: 'Official unconditional university admission letter required.',
      },
    ],
  },
  {
    id: 'task-102',
    task_name: 'Indian Passport Renewal Procedure (Tatkaal / Normal)',
    target_country: 'IND',
    status: 'READY_TO_SUBMIT',
    deadline: '2026-10-01',
    checklist_state: [
      {
        doc_type: 'PASSPORT',
        status: 'AVAILABLE',
        doc_id: 'doc-001',
        title: 'Current Booklet Copy',
        expiry_date: '2031-04-12',
        notes: 'Original booklet and self-attested copies ready.',
      },
      {
        doc_type: 'NATIONAL_ID',
        status: 'AVAILABLE',
        doc_id: 'doc-002',
        title: 'Aadhaar Identity Card',
        expiry_date: null,
        notes: 'Zero-knowledge masked identity proof verified.',
      },
      {
        doc_type: 'PROOF_OF_ADDRESS',
        status: 'AVAILABLE',
        doc_id: 'doc-002',
        title: 'Residential Address Verification',
        expiry_date: null,
        notes: 'Matches address in civil register.',
      },
    ],
  },
];
